### ISSUE TITLE
Break Neera (quest) in EET installation (replace NETRIG1.bcs)

### ISSUE THREAD

**Issue by simeonkosnitsky** [RoxanneSHS/BoneHill#1]
Break Neera (quest) in EET installation (replace NETRIG1.bcs)
Area BG1EE: OH2010
Break Rilsatrigger: 1460:1700
http://baldursgate.wikia.com/wiki/Neera_(quest)

**Comment by RoxanneSHS** [comment]
Netric1.bcs appears in BH and in Neera's quest with different content.
Renamed BH file to Door971.bcs (baf) and changed reference in BH2108.are to use the renamed script.
